language: scala
script: sbt ++$TRAVIS_SCALA_VERSION "testOnly * -- -exclude testCommands --"
scala:
  - "2.11.6"
  - "2.10.4"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
